services:
  web:
    image: legalstamp
    build:
      context: ..
      dockerfile: Dockerfile
      tags:
        - latest
    ports:
      - "3000:80"
    environment:
      # will be filled in k8s cluster
      K8S_APP__IMAGE_VERSION: "local"
      K8S_APP__IMAGE_REVISION: "00000000000000000"
      K8S_APP__VERSION: "v0.0.0"
