services:
  web:
    image: legalstamp
    build:
      context: ..
      args:
        K8S_APP__VERSION: "0.dev-compose"
        CANONICAL_URL: http://localhost
        LEGALSTAMP_AUTH_TOKEN: testtest
      tags:
        - latest
    ports:
      - "4321:80"
