{{- if eq .Values.legalstamp.auth.source "values" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.legalstamp.auth.secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
stringData:
  LEGALSTAMP_AUTH_TOKEN: {{ .Values.legalstamp.auth.values.LEGALSTAMP_AUTH_TOKEN }}
{{- end }}