name: Release

on:
  push:
    paths:
      - .helm/Chart.yaml # on maybe new app version
      - .github/workflows/release.yml

jobs:
  build-and-push:
    runs-on: ${{ vars.PREFERRED_RUNS_ON }}
    steps:
    #
    - uses: actions/checkout@v4

    #
    - name: Login to Private repository
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_PRIVATE_REGISTRY_DOMAIN }}
        username: ${{ secrets.DOCKER_PRIVATE_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_PRIVATE_REGISTRY_PASSWORD }}

    # 
    - name: Setup BuildX for faster builds
      uses: docker/setup-buildx-action@v3

    # 
    - name: Extract appVersion from Helm Chart
      id: helm-app-version
      run: |
        APP_VERSION=$(yq e '.appVersion' .helm/Chart.yaml)
        echo "appVersion=${APP_VERSION}" >> $GITHUB_OUTPUT

    - name: Extract and format allowed domains
      id: helm-allowed-cors
      run: |
        CORS_ALLOW_ORIGIN=$(yq -r '.cors.allowOriginFrom | join(",")' values.yaml)
        echo "allowed_cors=${CORS_ALLOW_ORIGIN}" >> $GITHUB_OUTPUT

    #
    - name: Compute full image location
      id: meta-pre
      run: |
        ORG_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(basename "${{ github.repository }}")
        echo "full_image_location=${{ vars.DOCKER_PRIVATE_REGISTRY_DOMAIN }}/${ORG_LOWER}/${REPO_NAME}" >> $GITHUB_OUTPUT
   
   #
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ steps.meta-pre.outputs.full_image_location }}
        tags: |
          type=ref,event=branch
          type=raw,value=${{ steps.helm-app-version.outputs.appVersion }},enable=${{ github.ref == 'refs/heads/main' }}
          type=raw,value=${{ github.ref_name }}-${{ steps.helm-app-version.outputs.appVersion }}
          type=raw,value=${{ steps.helm-app-version.outputs.appVersion }}-${{ github.ref_name }}
    
    #
    - name: Build and push
      id: build_image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        target: lean
        build-args: |
          K8S_APP__VERSION=${{ steps.helm-app-version.outputs.appVersion }}
          CORS_ALLOW_ORIGIN=${{ steps.helm-app-version.outputs.allowed_cors }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        #
        cache-from: type=registry,ref=${{ steps.meta-pre.outputs.full_image_location }}:cache
        cache-to: type=registry,ref=${{ steps.meta-pre.outputs.full_image_location }}:cache,image-manifest=true,oci-mediatypes=true,mode=max
        outputs: type=image,push=true
